Backend communications
ai-cfia/louis-smartsearch-frontend pull request #29
Opened 2023-07-06 19:15 UTC by CFIALeronB

- Creating dedicated api.js file that contains api call functions.
- Renaming function fecthData to PingBackend.
- Moved PingBackend to api.js
- Implemented on screen alert if empty query response is invalid.
- Moved and renamed api unit test file.

2023-07-06 20:25 UTC, rngadam commented on src/pages/home/Home.js
> +            console.error('The REACT_APP_BACKEND_URL environment variable is not set or empty.');
also an alert for the user "Backend URL is not set, frontend is misconfigured"

2023-07-06 20:26 UTC, rngadam commented on src/api/api.js
> +}
the little red marker at the end of files mean you are missing a new line

2023-07-06 20:27 UTC, rngadam commented on src/api/api.js
> +        } else{
your curly braces have inconsistent spacing. do:

```
} else {
```

2023-07-06 20:28 UTC, rngadam requested changes
see comments I left

2023-07-12 15:08 UTC, CFIALeronB commented on src/api/api.js
> +        } else{
@rngadam Fixed code indention

2023-07-13 14:56 UTC, rngadam commented on src/api/api.test.js
> +    if(url != ""){
spacing

2023-07-13 14:58 UTC, rngadam commented on src/api/useApiUtil.js
>                      console.log(resposeData);
misspelling

2023-07-13 15:00 UTC, rngadam commented on src/api/useApiUtil.js
> +            method: "POST",
PingBackend(get_endpoint) 
    fetch(get_endpoint('search'));

2023-07-13 23:16 UTC, rngadam requested changes
fix minor formatting issues

2023-07-14 14:56 UTC, rngadam approved these changes
LGTM

2023-07-14 15:11 UTC, merged